# Site settings
title: Blog gestión de la Configuración del Software
email: dfestrada@poligran.edu.co
description: > # this means to ignore newlines until "baseurl:"
  Este Blog Contiene inforamción sobre:
  Gestion de Configuración del Software
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.com/deyson12/deyson12.github.io" # the base hostname & protocol for your site
twitter_username: DeysonEstrada
github_username:  deyson12

# Build settings
markdown: kramdown
