name: Deploy Ventas 7 Lunas App to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'  # Ajusta según tu versión de Node.js
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build Angular app
      run: ng build --configuration=pdn
    
    - name: Copy index.html to 404.html
      run: cp docs/browser/index.html docs/browser/404.html
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'  # Solo despliega en push a main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/browser
        destination_dir: docs  # Esto coloca los archivos en la carpeta docs en la rama gh-pages