name: Build and Deploy Ventas 7 Lunas

on:
  push:
    branches:
      - main

permissions:
  contents: read        # sólo lectura de repo
  pages: write          # publicar en Pages
  id-token: write       # necesario para deploy-pages

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Clean docs folder
        run: rm -rf docs/*

      - name: Build PDN into docs
        run: npm run build -- --configuration=pdn --output-path=docs

      - name: Create SPA fallback & disable Jekyll
        run: |
          cp docs/index.html docs/404.html
          touch docs/.nojekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

  deploy-pages:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
