name: Build and Deploy Ventas 7 Lunas

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Clean docs folder
        run: rm -rf docs/*

      - name: Build PDN into docs
        run: npm run build -- --configuration=pdn

      - name: Create SPA fallback & disable Jekyll
        run: |
          cp docs/index.html docs/404.html
          touch docs/.nojekyll
      
      - name: Add legal static pages (return 200 on these routes)
        run: |
          mkdir -p docs/privacy-and-policy docs/service-condition
          cp legal/privacy-and-policy.html  docs/privacy-and-policy/index.html
          cp legal/service-condition.html   docs/service-condition/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
