name: CI/CD Angular → GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Clean previous docs
        run: rm -rf docs/*

      - name: Build PDN
        run: npm run build -- --configuration=pdn

      - name: Disable Jekyll
        run: touch docs/.nojekyll

      - name: Add SPA fallback
        run: cp docs/index.html docs/404.html

      - name: Commit & Push docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git diff --staged --quiet || git commit -m "ci: deploy docs [skip ci]"
          git push
